use std::time::{SystemTime, UNIX_EPOCH};
use uuid::Uuid;

pub fn now_secs() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TaskStatus {
    Queued,
    Running,
    NeedsReview,
    Done,
    Blocked,
    Interrupted,
}

impl std::fmt::Display for TaskStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            TaskStatus::Queued => "queued",
            TaskStatus::Running => "running",
            TaskStatus::NeedsReview => "needs_review",
            TaskStatus::Done => "done",
            TaskStatus::Blocked => "blocked",
            TaskStatus::Interrupted => "interrupted",
        };
        f.write_str(s)
    }
}

/// A unit of work on the board: a prompt handed to an agent within one project.
///
/// `id` (the task) and `session_id` (the ACP agent session) are deliberately
/// **separate** identifiers. Today a task has at most one session, but the
/// roadmap has multiple agents collaborating on a single task — so nothing
/// keys session state off the task id. Keeping them distinct now means that
/// future is additive (N sessions under a task), not a schema migration.
#[derive(Debug, Clone, PartialEq)]
pub struct Task {
    pub id: String,
    pub session_id: Option<String>,
    pub project: String,
    pub prompt: String,
    pub agent: String,
    pub status: TaskStatus,
    pub tags: Vec<String>,
    pub created_at: u64,
    pub updated_at: u64,
    pub files_changed: u32,
    pub blocked_reason: Option<String>,
}

impl Task {
    pub fn new(project: &str, prompt: &str, agent: &str, tags: Vec<String>) -> Self {
        let ts = now_secs();
        Self {
            id: format!("t_{}", &Uuid::new_v4().to_string()[..8]),
            session_id: None,
            project: project.to_string(),
            prompt: prompt.to_string(),
            agent: agent.to_string(),
            status: TaskStatus::Queued,
            tags,
            created_at: ts,
            updated_at: ts,
            files_changed: 0,
            blocked_reason: None,
        }
    }

    /// Attach an agent session to this task. The session id is generated by
    /// (or negotiated with) the ACP layer; it is never derived from `id`.
    pub fn attach_session(&mut self, session_id: String) {
        self.session_id = Some(session_id);
        self.status = TaskStatus::Running;
        self.updated_at = now_secs();
    }

    pub fn set_status(&mut self, status: TaskStatus) {
        self.status = status;
        self.updated_at = now_secs();
    }
}
