import { defineConfig } from "astro/config";
import tailwindcss from "@tailwindcss/vite";
import nimbus, { defineConfig as defineNimbusConfig } from "@cloudflare/nimbus-docs";
import { tableScroll } from "@cloudflare/nimbus-docs/markdown";

const nimbusConfig = defineNimbusConfig({
  // TODO: swap in the real docs domain once it's deployed (drives canonical
  // URLs, OG images, robots.txt, sitemap, and the links in /llms.txt).
  site: "https://docs.warpforge.dev",
  title: "Warpforge",
  description:
    "Run parallel coding agents without losing the workspace — docs for the Warpforge agentic development environment.",
  locale: "en",
  github: "https://github.com/ephor/warpforge",
  socialImageAlt: "Warpforge documentation preview",
  // Explicit order — the autogenerated default is alphabetical, which puts
  // Concepts ahead of Getting Started for a first-time reader.
  sidebar: {
    items: [
      "overview",
      { label: "Getting Started", autogenerate: { directory: "getting-started" } },
      { label: "Concepts", autogenerate: { directory: "concepts" } },
      { label: "Guides", autogenerate: { directory: "guides" } },
      { label: "Reference", autogenerate: { directory: "reference" } },
    ],
  },
});

export default defineConfig({
  output: "static",
  // Tailwind v4 via its Vite plugin (the integration Astro recommends for
  // Tailwind v4 — replaces the PostCSS plugin, which doesn't build under
  // Astro 7's Vite 8 bundler).
  vite: {
    plugins: [tailwindcss()],
  },
  // Hover-prefetch link targets so full-page navigations feel instant without
  // a client-side router.
  prefetch: {
    prefetchAll: true,
    defaultStrategy: "hover",
  },
  integrations: [
    nimbus(nimbusConfig, {
      // Authoring rules are opt-in by design — your repo, your taste. The
      // two below are the load-bearing pair: frontmatter has to validate
      // against the content schema for the page to render properly, and
      // broken internal links are 404s for your readers. Add the others
      // (heading hierarchy, code-block language, style, etc.) when you're
      // ready to enforce them — see `nimbus-docs lint --help`.
      rules: {
        "nimbus/frontmatter-shape": "error",
        "nimbus/internal-link": "error",
      },
      // Wrap wide tables so they scroll instead of overflowing the page
      // (styled by `.nb-table-scroll` in src/styles/prose.css).
      markdown: {
        hastPlugins: [tableScroll()],
      },
    }),
  ],
});
