import { defineConfig } from "astro/config";
import tailwindcss from "@tailwindcss/vite";
import react from "@astrojs/react";
import nimbus, { defineConfig as defineNimbusConfig } from "@cloudflare/nimbus-docs";
import { tableScroll } from "@cloudflare/nimbus-docs/markdown";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const WWW_SRC = resolve(HERE, "src");
const APP_SRC = resolve(HERE, "../desktop/src");

/**
 * Both this site and the desktop app spell their own source root `@/`, and the
 * landing page renders the app's real components — so one specifier has to mean
 * two different roots. Resolve it by who is importing, rather than rewriting
 * fifty-odd files in either tree. `@app/` is the explicit door from this site
 * into the app.
 *
 * A plugin rather than a `resolve.alias` entry because an alias hands back a
 * final path, which skips extension and index resolution (`@/components/ui/badge`
 * → `badge/index.ts`); delegating to `this.resolve` keeps it.
 *
 * One app module is swapped for a stub on the way through. The terminal is
 * xterm driven against a live PTY: CommonJS, so it will not prerender, and
 * with nothing to talk to on a static page. Its stand-in keeps the real
 * chrome and shows a fixed transcript. Everything else on the page — the
 * editor included, whose CodeMirror stays in its own lazy chunk — is the
 * app\'s own component.
 */
const APP_STUBS: Record<string, string> = {
  "components/runtime/TerminalWorkspace":
    "src/components/landing/demo/stubs/TerminalWorkspace.tsx",
};

function dualSourceAlias(): import("vite").Plugin {
  return {
    name: "warpforge-dual-source-alias",
    enforce: "pre",
    async resolveId(source, importer, options) {
      const root = source.startsWith("@app/")
        ? APP_SRC
        : source.startsWith("@/")
          ? importer?.includes(`${sep}desktop${sep}src${sep}`)
            ? APP_SRC
            : WWW_SRC
          : null;
      const fromApp = importer?.includes(`${sep}desktop${sep}src${sep}`) ?? false;

      // A bare specifier imported by the app would otherwise resolve out of
      // `desktop/node_modules`, giving the page two copies of React, React
      // Query and Zustand — two contexts, and every hook that crosses the seam
      // throws. This site installs the app's dependencies at the app's
      // versions, so route those imports here and keep one of everything.
      if (!root && fromApp && !source.startsWith(".")) {
        const here = await this.resolve(source, resolve(WWW_SRC, "_.ts"), {
          ...options,
          skipSelf: true,
        });
        // Returning null would let Vite resolve it from the app's own tree
        // instead, quietly restoring the duplicate this branch exists to
        // prevent — and a duplicated React or store fails at runtime, long
        // after the build said it was fine. Say so now instead.
        if (!here) {
          throw new Error(
            `www: ${importer} imports "${source}", which this site does not install. ` +
              `Add it to www/package.json at the version desktop/package.json uses — ` +
              `resolving it from the app's tree would give the page two copies.`,
          );
        }
        return here;
      }

      const target = root
        ? resolve(root, source.slice(source.startsWith("@app/") ? 5 : 2))
        : fromApp && source.startsWith(".")
          ? resolve(dirname(importer!), source)
          : null;
      if (!target) return null;
      const stub = APP_STUBS[relative(APP_SRC, target).split(sep).join("/")];
      if (stub) return this.resolve(resolve(HERE, stub), importer, { ...options, skipSelf: true });
      return this.resolve(target, importer, { ...options, skipSelf: true });
    },
  };
}

const nimbusConfig = defineNimbusConfig({
  // Drives canonical URLs, OG images, robots.txt, sitemap, and the links in
  // /llms.txt. The landing page is `/`; the docs live under it.
  site: "https://warpforge.app",
  title: "Warpforge",
  description:
    "Run parallel coding agents without losing the workspace — docs for the Warpforge agentic development environment.",
  locale: "en",
  github: "https://github.com/ephor/warpforge",
  socialImageAlt: "Warpforge documentation preview",
  // Explicit order — the autogenerated default is alphabetical, which puts
  // Concepts ahead of Getting Started for a first-time reader.
  sidebar: {
    items: [
      "overview",
      { label: "Getting Started", autogenerate: { directory: "getting-started" } },
      { label: "Concepts", autogenerate: { directory: "concepts" } },
      { label: "Guides", autogenerate: { directory: "guides" } },
      { label: "Reference", autogenerate: { directory: "reference" } },
    ],
  },
});

export default defineConfig({
  output: "static",
  // Tailwind v4 via its Vite plugin (the integration Astro recommends for
  // Tailwind v4 — replaces the PostCSS plugin, which doesn't build under
  // Astro 7's Vite 8 bundler).
  vite: {
    plugins: [dualSourceAlias(), tailwindcss()],
  },
  // Hover-prefetch link targets so full-page navigations feel instant without
  // a client-side router.
  prefetch: {
    prefetchAll: true,
    defaultStrategy: "hover",
  },
  integrations: [
    react(),
    nimbus(nimbusConfig, {
      // Authoring rules are opt-in by design — your repo, your taste. The
      // two below are the load-bearing pair: frontmatter has to validate
      // against the content schema for the page to render properly, and
      // broken internal links are 404s for your readers. Add the others
      // (heading hierarchy, code-block language, style, etc.) when you're
      // ready to enforce them — see `nimbus-docs lint --help`.
      rules: {
        "nimbus/frontmatter-shape": "error",
        "nimbus/internal-link": "error",
      },
      // Wrap wide tables so they scroll instead of overflowing the page
      // (styled by `.nb-table-scroll` in src/styles/prose.css).
      markdown: {
        hastPlugins: [tableScroll()],
      },
    }),
  ],
});
